### ISSUE TITLE
Flip parameters of Dict.get 

### ISSUE THREAD

**Issue by Janiczek** [elm/core#1025]
I propose to flip parameters of `Dict.get`:

```elm
-- current
get : comparable -> Dict comparable a -> Maybe a
-- becomes
get : Dict comparable a -> comparable -> Maybe a
```

The motivation is `Dict.get` (well, along with `Set.member`) consistently being the one reason I resort to using `flip`:

```elm
getKey foo bar
  |> Maybe.andThen (flip Dict.get dict)
```

(Alternatives being a lambda, or defining a helper like `getIn` with the parameters flipped.)

I was asking folks in #general on the Elm Slack, and @zwilias had this comment:
> Ilias [18:36]
> I think there's a point to be made for changing it in the core package. We put the "thing to transform" last for pipeline friendliness. Based on my experience, it's the key that's usually being transformed, not the dict.
> So long story short - yeah, agreed

Would this be something worthwhile to change?

**Comment by evancz** [comment]
The cost to users would be extremely high, so I think it's only viable to consider for a major release.

I also do not really like this idea, partly because it raises consistency questions about what should happen with `Dict.member`, `Dict.remove`, etc. As things are, you can always expect the key to come before the dictionary, so there is never any weirdness to remember.

My experience from using the `!` operator in Haskell's `Map` library (which flips the arguments) is that it is confusing and not worth it. To me at least!

**Comment by Janiczek** [comment]
To clarify, I didn't intend to introduce an inconsistency by changing just one function - those other functions (`member`, `remove`, ...) would have to change as well, for sure.

Thanks for the reply!
