### ISSUE TITLE
modBy gives runtime error when called with zero divident

### ISSUE THREAD

**Issue by decafbad** [elm/core#1034]
> Basics.modBy 0 3
> Error: Cannot perform mod 0. Division by zero error.

Besides that, its sibling returns an impossible thing 
> Basic.remainderBy 0 3
> NaN : Int

**Comment by jvoigtlaender** [comment]
Actually, the `0` in `Basics.modBy 0 3` is the divisor, not the dividend.

Also: https://github.com/elm/core/issues/590, https://github.com/elm/core/issues/721.

**Comment by decafbad** [comment]
NaN : Int isn't ok for me. Thanks.

**Comment by harrysarson** [comment]
The fact that `Basics.remainderBy` returns `NaN` makes sense if you look at [its definition]
(https://github.com/elm/core/blob/master/src/Elm/Kernel/Basics.js#L17):

```js
var _Basics_remainderBy = F2(function(b, a) { return a % b; });
```

I don't think this behaviour is intentional - as elm is compiled into (untyped) javascript such strange results as this will happen from time to time.
