### ISSUE TITLE
operator not self-explanatory  9 // 2

### ISSUE THREAD

**Issue by zzz6519003** [elm/core#1039]
`> 9 // 2`

**Comment by Erudition** [comment]
...um, that's why it's in the docs?

> `(//) : Int -> Int -> Int`
> Integer division:
> `3 // 2 == 1`
> Notice that the remainder is discarded.

**Comment by evancz** [comment]
Hey, can you say a bit more about how you came across this operator? Is there something that could be added that would make it easier? Perhaps in the documentation or elsewhere.

A lot of documentation is available on https://package.elm-lang.org/ but I can imagine that the notes about this operator [here](https://package.elm-lang.org/packages/elm/core/latest/Basics#//) can be really hard to find.

Please let me know more about your situation so we can try to think of ways to make it less confusing!

**Comment by zzz6519003** [comment]
we could remove(reserve) it

**Comment by Gabgab2003** [comment]
As another user whose comment has been removed said. The // operator is in the docs. But you have a point. Unlike the / operator which every kid learns in school // is not taught in school because its not general. But if we follow that logic we would have to remove ^ as exponent as in school we learn that superscript is the way to annotate exponents. The // operator has its roots in python as far as I know and most people know it from python. Integer dividing is important in the Web for styling things, so making the operator longer wouldn't be great as it would add unnecessary complexity. In Morse for example the e is a single dit (.), because it is used often. If the e were let's say dit dit dah dit (..-.) it would be slow to Morse. Same applies to programming language. Verbose features tend to be used less/only if needed. Elm language design respects that
