### ISSUE TITLE
NaN == NaN is False

### ISSUE THREAD

**Issue by lawsdontapplytopigs** [elm/core#1044]
In the repl:
```elm
> (0/0)
-- NaN : Float
> (0/0) == (0/0)
-- False : Bool
> (0/0) /= (0/0)
-- True : Bool
```
Shouldn't `NaN == NaN` return `True`
and `NaN /= NaN` return `False`?

**Comment by harrysarson** [comment]
This is documented here: https://package.elm-lang.org/packages/elm/core/latest/Basics#Float

**Comment by BrianHicks** [comment]
Hi @lawsdontapplytopigs, you're right that this is weird! The takeaway here is that for efficiency's sake, Elm uses IEEE 754 floating-point numbers. We do this because JS does, but you can trace this particular technical decision all the way down to CPU instructions. We couldn't change this without reimplementing numerical computation or our own hardware, which would either be super slow or economically infeasible.

Historically, this happened because `isNaN` was invented some time after the introduction of NaN. That meant to detect NaN (for example to halt early when further computation was pointless) they had to special case some mathematical. To make a long story short, they chose equality. It's always true that `x == x` *except* in the case of NaN. So before `isNaN` existed, you could just compare your intermediate value to itself—if that returned `False` then you had a NaN! Of course now we have `isNaN` but in the intervening time it got built into CPU instructions so now we will just have this particular quirk forever, probably.

If you are running into trouble implementing a specific thing because of NaN, feel free to ask in Slack (I think I saw you on there.) Happy elming!

**Comment by lawsdontapplytopigs** [comment]
Oh I see! Thanks a lot for the thorough explanation, Brian! No, there wasn't anything I couldn't do because of NaN, it's just that it looked like a bug. If I find something, however, I'll let you know on Slack!
