### ISSUE TITLE
Bitwise.shiftLeft returns wrong value for 0.

### ISSUE THREAD

**Issue by NikosEfthias** [elm/core#1074]
`Bitwise.shiftLeft 1 0` is expected to return 1 however the return value is 0
[here](https://ellie-app.com/7wSnpmcxyT7a1) is a reproducable example

**Comment by rlefevre** [comment]
There is no `Bitwise.shiftLeft` since `elm-lang/core 5.0.0` in Elm 0.18.

Currently in Elm 0.19, `elm/core` package only has [`shiftLeftBy`](https://package.elm-lang.org/packages/elm/core/latest/Bitwise#shiftLeftBy), and the documentation is clear that shifting 0 to the left by one bit will give 0, not 1 (the first argument being offset, and new bits being filled with 0):
> Shift bits to the left by a given offset, filling new bits with zeros. This can be used to multiply numbers by powers of two.

Maybe you are using a very old version, or are confused by the order of the arguments?

**Comment by NikosEfthias** [comment]
Oh I just mixed the argument order sorry for the trouble
