### ISSUE TITLE
Could Task.mapN launch all tasks at the same time?

### ISSUE THREAD

**Issue by ldesgoui** [elm/core#990]
Hello,

```elm
loadD : Cmd Msg
loadD =
    Task.map3
        (\a b c -> a + b + c)
        (Http.get (apiA) decodeA |> Http.toTask)
        (Http.get (apiB) decodeB |> Http.toTask)
        (Http.get (apiC) decodeC |> Http.toTask)
        |> Task.perform Api
```
I just wrote something like the code above and I expected all tasks to begin at the same time since neither depend on each other, I found out that `mapN` are implemented using lambdas and `andThen`.
Can it be done (would anything break?), should it be done (will it cause regression in certain cases?), and should I attempt to implement an update? I'm also absolutely fine with a response like "I haven't had the time to research this yet", in which case I'll come back with the research done if wanted

Thanks!

**Comment by evancz** [comment]
The trouble is that `Task` is not just for HTTP. It is for any kind of effect, so if there were ever a way to read and write files, you would definitely care that certain things happened before or after other things. This is true with HTTP as well (e.g. with PUT requests) but it is a less obvious scenario because it is less common overall.

Point is, it would clash with the intended design of tasks. There are other ways to accomplish parallel requests with API changes, but at the moment, the best way is (1) to have the endpoint provide the data you need in one request or (2) to have multiple commands that ask for the data however is needed. I understand that this could potentially be more convenient though.

In the future, questions like this work best on https://discourse.elm-lang.org/

**Comment by ldesgoui** [comment]
Oops, forgot about the forum. Thanks for the answer
